2021-07-11 13:31:31,110 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:46]
2021-07-11 13:31:37,950 ERROR: Exception on /edit_profile [POST] [in /home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nakoibes/Рабочий стол/APP/app/routes.py", line 97, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
    flush_context.execute()
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 234, in save_obj
    _emit_update_statements(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 998, in _emit_update_statements
    c = connection._execute_20(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/nakoibes/Рабочий стол/APP/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('mario', '', 2)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
2021-07-11 18:45:14,954 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:46]
2021-07-11 18:46:37,594 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:46]
2021-07-12 19:39:18,216 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:46]
2021-07-15 15:29:17,692 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:30:14,745 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,589 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,619 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,619 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,668 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,668 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,668 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,719 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,719 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,719 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:43:48,719 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,007 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,036 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,036 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,084 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,084 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,084 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,136 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,136 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,136 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
2021-07-15 15:44:20,136 INFO: Microblog startup [in /home/nakoibes/Рабочий стол/APP/app/__init__.py:70]
